#!/usr/bin/python3
from sys import argv
from decimal import Decimal
import math

def main():
    with open(argv[1], encoding="utf-8") as file_:
        for i in file_.readlines():
            num = int(i)
            mod = factor(num)
            print("{}={}*{}".format(num, int(num // mod), int(mod)))

def factor(n):
    x, y, l, d = 2, 2, 1, 1
    g = lambda x: (x**2 + l) % n
    while d == 1:
        x = g(x)
        y = g(g(y))
        d = math.gcd(abs(x - y), n)
    return d
main()
